import {SVGProps} from "react";

export function SpinnerIcon({
                                rectClassName,
                                ...props
                            }: SVGProps<SVGSVGElement> & { rectClassName?: string }) {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 100 100"
            preserveAspectRatio="xMidYMid"
            width="165"
            height="165"
            {...props}
        >
            <g>
                <g transform="rotate(0 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.4964539007092198s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(24 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.4609929078014184s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(48 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.42553191489361697s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(72 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.39007092198581556s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(96 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.35460992907801414s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(120 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.3191489361702127s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(144 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.2836879432624113s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(168 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.2482269503546099s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(192 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.21276595744680848s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(216 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.17730496453900707s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(240 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.14184397163120566s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(264 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.10638297872340424s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(288 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.07092198581560283s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(312 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="-0.035460992907801414s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g transform="rotate(336 50 50)">
                    <rect
                        fill="#000000"
                        className={rectClassName}
                        height="10"
                        width="5"
                        ry="1.5"
                        rx="1.5"
                        y="27"
                        x="47.5"
                    >
                        <animate
                            repeatCount="indefinite"
                            begin="0s"
                            dur="0.5319148936170213s"
                            keyTimes="0;1"
                            values="1;0"
                            attributeName="opacity"
                        ></animate>
                    </rect>
                </g>
                <g></g>
            </g>
        </svg>
    );
}